#!/bin/bash
# Quick Usage Guide

echo "====================================="
echo "  Kudu Docker Environment - Quick Guide"
echo "====================================="
echo ""
echo "1. Start environment:"
echo "   ./start.sh"
echo ""
echo "2. Access Web UI:"
echo "   Master UI:  http://localhost:8051"
echo "   TServer UI: http://localhost:8050"
echo ""
echo "3. Connect from host (Python):"
echo "   First install: pip install kudu-python"
echo "   Connection address: localhost:7051"
echo ""
echo "4. Stop environment:"
echo "   ./stop.sh"
echo ""
echo "5. View table data:"
echo "   python3 init-kudu.py  # Re-run initialization"
echo ""
echo "Created tables:"
echo "  - test.tbl1 (user table): id, name, age, email, created_at"
echo "  - test.tbl2 (product table): product_id, product_name, price, quantity, category"
echo ""
echo "For detailed documentation, see README.md"
echo "====================================="
